[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -v"
testpaths = [
    "data/tests",
]
filterwarnings = [
    "ignore::DeprecationWarning",
]

log_cli = true
log_cli_level = "CRITICAL"
log_cli_format = "%(message)s"
log_file_level = "INFO"
log_file_format = "%(asctime)s %(name)s %(levelname)s %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
required_plugins = ""
junit_duration_report = "total"
junit_family = "xunit2"
junit_logging = "all"
junit_log_passing_tests = true
junit_suite_name = "ostest"